export const orderScreenButtonName = {
    ORDER_BUY_BUTTON_NAME:"BUY",
    ORDER_SELL_BUTTON_NAME:"SELL",
    ORDER_REJECTED_BUTTON_NAME:"REJECTED",
    ORDER_PENDING_BUTTON_NAME:"PENDING",
    ORDER_COMPLETE_BUTTON_NAME:"COMPLETE",
    ORDER_CANCELLED_BUTTON_NAME:"CANCELLED"
}