import { STOCK_SEARCH_COLORS } from "../types/global";
import { ORDER_SCREEN_COLORS } from "../types/order";

export const orderColors:ORDER_SCREEN_COLORS = {
    ORDER_BUY_TAG_BACKGROUND_COLOR:"#daf3f7",
    ORDER_BUY_TAG_TEXT_COLOR:"#0076c8",
    ORDER_SELL_TAG_TEXT_COLOR:'#b50000',
    ORDER_SELL_TAG_BACKGROUND_COLOR:"#f9e5e5",
    ORDER_PENDING_STATUS_BACKGROUND_COLOR:"",
    ORDER_REJECTED_STATUS_BACKGROUND_COLOR:"#f9e5e5",
    ORDER_COMPLETED_STATUS_BACKGROUND_COLOR:"#e3f8dd",
    ORDER_COMPLETED_STATUS_TEXT_COLOR:"#218f01",
    ORDER_PENDING_STATUS_TEXT_COLOR:"",
    ORDER_REJECTED_STATUS_TEXT_COLOR:"#b50000",
    ORDER_CANCELLED_STATUS_BACKGROUND_COLOR:"",
    ORDER_CANCELLED_STATUS_TEXT_COLOR:""
}


export const STOCK_SEARCH_SCREEN_COLORS:STOCK_SEARCH_COLORS = {
    STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR:"#daf3f7",
    STOCK_SEARCH_BSE_TAG_TEXT_COLOR:"#0076c8",
    STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR:"#f9e5e5",
    STOCK_SEARCH_NSE_TAG_TEXT_COLOR:"#b50000",
    STOCK_SEARCH_ADD_BUTTON_COLOR:"#0076c8",
    STOCK_SCREEN_CHECK_BUTTON_COLOR:"#2cbb02"
}