import { ORDER_SCREEN_COLORS } from "../types/order";

export const orderColors:ORDER_SCREEN_COLORS = {
    ORDER_BUY_TAG_BACKGROUND_COLOR:"#daf3f7",
    ORDER_BUY_TAG_TEXT_COLOR:"#0076c8",
    ORDER_SELL_TAG_TEXT_COLOR:'#b50000',
    ORDER_SELL_TAG_BACKGROUND_COLOR:"#f9e5e5",
    ORDER_PENDING_STATUS_BACKGROUND_COLOR:"",
    ORDER_REJECTED_STATUS_BACKGROUND_COLOR:"#f9e5e5",
    ORDER_COMPLETED_STATUS_BACKGROUND_COLOR:"#e3f8dd",
    ORDER_COMPLETED_STATUS_TEXT_COLOR:"#218f01",
    ORDER_PENDING_STATUS_TEXT_COLOR:"",
    ORDER_REJECTED_STATUS_TEXT_COLOR:"#b50000",
    ORDER_CANCELLED_STATUS_BACKGROUND_COLOR:"",
    ORDER_CANCELLED_STATUS_TEXT_COLOR:""
}