export type RootStackParamList = {
    HomeScreen: undefined;
    FundScreen:undefined;
}

export type WATCHLIST_SCREEN_HEADER_TITLE = "WatchList";
export type ORDERS_SCREEN_HEADER_TITLE = "Orders";
export type PORTFOLIO_SCREEN_HEADER_TITLE  = "Portfolio"
export type BID_SCREEN_HEADER_TITLE = "Bids";
export type ACCOUNT_SCREEN_HEADER_TITLE = "Account";


export interface HEADER_PRIMARY_SCREEN_TITLE {
    WATCHLIST:WATCHLIST_SCREEN_HEADER_TITLE,
    ORDERS:ORDERS_SCREEN_HEADER_TITLE,
    PORTFOLIO:PORTFOLIO_SCREEN_HEADER_TITLE,
    BIDS:BID_SCREEN_HEADER_TITLE,
    ACCOUNT:ACCOUNT_SCREEN_HEADER_TITLE
}


type STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR = '#daf3f7';
type STOCK_SEARCH_BSE_TAG_TEXT_COLOR = "#0076c8";
type STOCK_SEARCH_NSE_TAG_TEXT_COLOR = '#b50000';
type STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR = "#f9e5e5";
type STOCK_SCREEN_ADD_BUTTON_COLOR = "#0076c8"
type STOCK_SCREEN_CHECK_BUTTON_COLOR = "#2cbb02"

export interface STOCK_SEARCH_COLORS {
    STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR:STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR,
    STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR:STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR,
    STOCK_SEARCH_NSE_TAG_TEXT_COLOR:STOCK_SEARCH_NSE_TAG_TEXT_COLOR,
    STOCK_SEARCH_BSE_TAG_TEXT_COLOR:STOCK_SEARCH_BSE_TAG_TEXT_COLOR,
    STOCK_SEARCH_ADD_BUTTON_COLOR:STOCK_SCREEN_ADD_BUTTON_COLOR,
    STOCK_SCREEN_CHECK_BUTTON_COLOR:STOCK_SCREEN_CHECK_BUTTON_COLOR

}