export type RootStackParamList = {
    HomeScreen: undefined;
    FundScreen:undefined;
}

// export type WATCHLIST_SCREEN_HEADER_TITLE = "WatchList";
// export type ORDERS_SCREEN_HEADER_TITLE = "Orders";
// export type PORTFOLIO_SCREEN_HEADER_TITLE  = "Portfolio"
// export type BID_SCREEN_HEADER_TITLE = "Bids";
// export type ACCOUNT_SCREEN_HEADER_TITLE = "Account";


// export interface HEADER_PRIMARY_SCREEN_TITLE {
//     WATCHLIST:WATCHLIST_SCREEN_HEADER_TITLE,
//     ORDERS:ORDERS_SCREEN_HEADER_TITLE,
//     PORTFOLIO:PORTFOLIO_SCREEN_HEADER_TITLE,
//     BIDS:BID_SCREEN_HEADER_TITLE,
//     ACCOUNT:ACCOUNT_SCREEN_HEADER_TITLE
// }

export enum HEADER_PRIMARY_SCREEN_TITLE {
    WATCHLIST="WatchList" ,
    ORDERS= "Orders",
    PORTFOLIO = "Portfolio",
    BIDS="Bids",
    ACCOUNT="Account"
}


//stock search screen
type STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR = '#daf3f7';
type STOCK_SEARCH_BSE_TAG_TEXT_COLOR = "#0076c8";
type STOCK_SEARCH_NSE_TAG_TEXT_COLOR = '#b50000';
type STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR = "#f9e5e5";
type STOCK_SCREEN_ADD_BUTTON_COLOR = "#0076c8"
type STOCK_SCREEN_CHECK_BUTTON_COLOR = "#2cbb02"

//buy/sell Screen

type BUY_SCREEN_BUTTON_SELECTED_BORDER_AND_TEXT_COLOR = "#2a8af4";
type BUY_SCREEN_BUTTON_UNSELECTED_DEFAULT_BORDER_AND_TEXT_COLOR = "lightgray";







//stock search screen object
export interface STOCK_SEARCH_COLORS {
    STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR:STOCK_SEARCH_BSE_TAG_BACKGROUND_COLOR,
    STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR:STOCK_SEARCH_NSE_TAG_BACKGROUND_COLOR,
    STOCK_SEARCH_NSE_TAG_TEXT_COLOR:STOCK_SEARCH_NSE_TAG_TEXT_COLOR,
    STOCK_SEARCH_BSE_TAG_TEXT_COLOR:STOCK_SEARCH_BSE_TAG_TEXT_COLOR,
    STOCK_SEARCH_ADD_BUTTON_COLOR:STOCK_SCREEN_ADD_BUTTON_COLOR,
    STOCK_SCREEN_CHECK_BUTTON_COLOR:STOCK_SCREEN_CHECK_BUTTON_COLOR

}

//buy/sell screen object

export interface BUY_SELL_SCREEN_COLORS {
    BUY_SCREEN_BUTTON_SELECTED_BORDER_AND_TEXT_COLOR:BUY_SCREEN_BUTTON_SELECTED_BORDER_AND_TEXT_COLOR;
    BUY_SCREEN_BUTTON_UNSELECTED_DEFAULT_BORDER_AND_TEXT_COLOR:BUY_SCREEN_BUTTON_UNSELECTED_DEFAULT_BORDER_AND_TEXT_COLOR;
    

}






//api codes

export interface API_RESPONSE_DEFAULT {
    error:boolean;
    info:string;
    data?:any;
}


export interface API_RESPONSE_DEFAULT_ALL<T> {
    error:boolean;
    info:string,
    data?:T;
}