export type orderStatusPrimary = ORDER_PENDING_STATUS | ORDER_REJECTED_STATUS | ORDER_COMPLETE_STATUS | ORDER_CANCELLED_STATUS;

export type orderTypePrimary = ORDER_TYPE_BUY | ORDER_TYPE_SELL;

//order_status
export type ORDER_COMPLETE_STATUS = "completed";
export type ORDER_REJECTED_STATUS = "rejected";
export type ORDER_PENDING_STATUS = "pending";
export type ORDER_CANCELLED_STATUS = "cancelled";

//order_type
export type ORDER_TYPE_BUY = "buy";
export type ORDER_TYPE_SELL = "sell";


//colors
type ORDER_BUY_TAG_BACKGROUND_COLOR = '#daf3f7';
type ORDER_BUY_TAG_TEXT_COLOR = "#0076c8";
type ORDER_SELL_TAG_TEXT_COLOR = '#b50000';
type ORDER_SELL_TAG_BACKGROUND_COLOR = "#f9e5e5";
type ORDER_PENDING_STATUS_BACKGROUND_COLOR = "";
type ORDER_REJECTED_STATUS_BACKGROUND_COLOR = ORDER_SELL_TAG_BACKGROUND_COLOR;
type ORDER_COMPLETED_STATUS_BACKGROUND_COLOR = "#e3f8dd";
type ORDER_PENDING_STATUS_TEXT_COLOR = "";
type ORDER_REJECTED_STATUS_TEXT_COLOR = ORDER_SELL_TAG_TEXT_COLOR;
type ORDER_COMPLETED_STATUS_TEXT_COLOR = "#218f01";
type ORDER_CANCELLED_STATUS_BACKGROUND_COLOR ="";
type ORDER_CANCELLED_STATUS_TEXT_COLOR = "";


export interface ORDER_SCREEN_FLAGS_AND_STATUS {
    COMPLETED: ORDER_COMPLETE_STATUS,
    PENDING: ORDER_PENDING_STATUS,
    REJECTED: ORDER_REJECTED_STATUS,
    CANCELLED:ORDER_CANCELLED_STATUS,
    BUY_ORDER: ORDER_TYPE_BUY,
    SELL_ORDER: ORDER_TYPE_SELL
}


export interface ORDER_SCREEN_COLORS {
    ORDER_BUY_TAG_BACKGROUND_COLOR: ORDER_BUY_TAG_BACKGROUND_COLOR,
    ORDER_BUY_TAG_TEXT_COLOR: ORDER_BUY_TAG_TEXT_COLOR,
    ORDER_SELL_TAG_TEXT_COLOR: ORDER_SELL_TAG_TEXT_COLOR,
    ORDER_SELL_TAG_BACKGROUND_COLOR: ORDER_SELL_TAG_BACKGROUND_COLOR,
    ORDER_PENDING_STATUS_BACKGROUND_COLOR: ORDER_PENDING_STATUS_BACKGROUND_COLOR,
    ORDER_REJECTED_STATUS_BACKGROUND_COLOR: ORDER_REJECTED_STATUS_BACKGROUND_COLOR,
    ORDER_COMPLETED_STATUS_BACKGROUND_COLOR: ORDER_COMPLETED_STATUS_BACKGROUND_COLOR,
    ORDER_PENDING_STATUS_TEXT_COLOR: ORDER_PENDING_STATUS_TEXT_COLOR;
    ORDER_REJECTED_STATUS_TEXT_COLOR: ORDER_REJECTED_STATUS_TEXT_COLOR;
    ORDER_COMPLETED_STATUS_TEXT_COLOR: ORDER_COMPLETED_STATUS_TEXT_COLOR;
    ORDER_CANCELLED_STATUS_BACKGROUND_COLOR :"",
    ORDER_CANCELLED_STATUS_TEXT_COLOR : ""
}

export type ORDER_FULL_BACKGROUND_COLORS = ORDER_BUY_TAG_BACKGROUND_COLOR |  ORDER_SELL_TAG_BACKGROUND_COLOR | ORDER_CANCELLED_STATUS_BACKGROUND_COLOR | ORDER_COMPLETED_STATUS_BACKGROUND_COLOR | ORDER_PENDING_STATUS_BACKGROUND_COLOR | ORDER_REJECTED_STATUS_BACKGROUND_COLOR ;
export type ORDER_FULL_TEXT_COLORS = ORDER_BUY_TAG_TEXT_COLOR | ORDER_SELL_TAG_TEXT_COLOR | ORDER_CANCELLED_STATUS_TEXT_COLOR | ORDER_COMPLETED_STATUS_TEXT_COLOR | ORDER_PENDING_STATUS_TEXT_COLOR | ORDER_REJECTED_STATUS_TEXT_COLOR;  


export interface HANDLE_ORDER_STATUS_FUNC_PROPS {
    BACKGROUND_COLOR?:ORDER_FULL_BACKGROUND_COLORS,
    TEXT_COLOR?:ORDER_FULL_TEXT_COLORS,
    BUTTON_TITLE?:string

}