export interface STOCK {
    _id:string;
    name: string;
    complete_name:string;
    current_price:string;
    stock_link: string;
    description: string;
    open: string;
    previous_close: string;
    volume: string;
    value: string;
    vwap: string;
    beta: string;
    market_cap: string;
    high: string;
    low: string;
    uc_limit: string;
    lc_limit: string;
    week_high_52: string;
    week_low_52: string;
    face_value: string;
    all_time_high: string;
    all_time_low: string;
    avg_volume_20days: string;
    avg_delivery_20days: string;
    book_value_per_share: string;
    dividend_yield: string;
    ttm_eps: string;
    ttm_pe: string;
    pb: string;
    sector_pe: string;
}